### ISSUE TITLE
I'm unsure how to categorise those communites. 

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#12]
I know that they will go to the art section but can't tell where exactly. Should they go to general artworks or maybe get their own section? 

https://lemmy.world/c/wizards Artworks of wizards mixed with memes with wizards. When's the line telling us to put it in memes or artworks?

https://lemmy.world/c/architecture This one will probably need a new section but what would that section be?

https://lemmy.world/c/roomporn Should this go into photography or to the same section as architecture? (assuming it gets the new section)

**Comment by chris-y** [comment]
Last one photography for sure. 
Architecture maybe there was well? 
Wizards is an odd one as it's a bit of a mix.

**Comment by chris-y** [comment]
Wizards could go in a section with goblincore@lemmy.blahaj.zone

**Comment by M4rtineski** [comment]
Please link communities in URL format so I can open them from github. 😭

**Comment by M4rtineski** [comment]
Yeah, they should go in the same section. We will need to come up with a proper section for that though.

**Comment by M4rtineski** [comment]
![image](https://github.com/fnic-lemmy/lemmy-directory/assets/137183342/d98d4c82-1388-4baa-b23d-404e9005a3cb)
 
https://sh.itjust.works/c/vaporwave This community would fit with goblincore and wizards. I'm starting to notice a pattern and get an idea in mind. Those are themes that can be shared in different formats. Basically "themes" category in art section would be more or less a fitting name for those communities. We can always rename it to something else along the way.

**Comment by M4rtineski** [comment]
Anotha one: https://lemmy.world/c/fancyaesthetics

**Comment by M4rtineski** [comment]
Alright. In the next update I will implement "Themes" section and add other communities to "Photography" section with a question mark to figure it along the way.

**Comment by M4rtineski** [comment]
This was already done.
