### ISSUE TITLE
Add a second post/file

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/lemmy-directory#18]
A second file needs adding to allow the directory to be split over multiple posts.

**Comment by M4rtineski** [comment]
Reason: we will hit post char limit soon.

**Comment by chris-y** [comment]
Done.  If you edit [Directory2.md](https://github.com/fnic-lemmy/lemmy-directory/blob/main/Directory2.md) it will now push up to [Directory post 2](https://lemmy.dbzer0.com/post/22390186)

Remember you can edit the titles [here](https://github.com/fnic-lemmy/lemmy-directory/settings/variables/actions) (POST_TITLE and POST2_TITLE)

**Comment by chris-y** [comment]
Yes. I assume the API needs to be provided with a title, nighed set this up (I just changed it to a var to make it easier to edit).

**Comment by chris-y** [comment]
Just to clarify, you need to make a change to the main body too to get the title change to push, as that doesn't trigger an update.
