### ISSUE TITLE
Do you think if we should drop the idea of direct community links to save character space?

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#19]
It's rather easy to visit the original instance from different fediverse platforms and I don't think people would use it anyway. Redirects keeping you on your instance seem the most important to keep to me.

**Comment by chris-y** [comment]
In the app I use (connect) the direct links open in app, whereas the lemmyverse.link ones open in an external browser, so I'm very much of the opinion that the direct links should stay.

**Comment by M4rtineski** [comment]
I think there was an app to open links in preferred mobile app or something along the lines. Will try looking it up to see if it would work with lemmyverse.

Can you tell me what's the use case of opening the community directly from instance that's not your not home instance though?

**Comment by chris-y** [comment]
Maybe I've misunderstood what you meant by "direct community links"?

**Comment by M4rtineski** [comment]
Direct link: https://lemmy.ml/c/imaginarymaps

Non-direct link: https://lemmy.world/c/imaginarymaps@lemmy.ml

**Comment by chris-y** [comment]
Ok, yeah, the direct link can probably be dropped.

17 Jun 2024 18:33:32 M4rtineski ***@***.***>:

**Comment by M4rtineski** [comment]
Issue closed. I will take the task onto myself not to implement those links. Damn, am I working hard.
