### ISSUE TITLE
Can't test kbin links to lemmy communities because directory posts didn't federate to kbin.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#2]
![image](https://github.com/fnic-lemmy/lemmy-directory/assets/137183342/718877f4-49d3-45df-aee0-d85c38d3f091)

Will need to wait and see if this changes with time but until then I can't really start setting up kbin links.

**Comment by M4rtineski** [comment]
If kbin instances federate only new posts we can remove the directory post and create it anew every so often to make it federate with more instances.

**Comment by chris-y** [comment]
Kbin has real problems with bots and doesn't get history when searching up a new community. 

I checked Mbin and that does show the post, but it's the original version. I didn't try subscribing, that may update it. 

![Screenshot_20240613-174006-944.png](https://github.com/fnic-lemmy/lemmy-directory/assets/1818803/6ecfcec6-1d09-4559-9e83-52e5bc63a913)

https://fedia.io/m/lemmydirectory@lemmy.dbzer0.com/t/886510/Lemmy-Directory

**Comment by chris-y** [comment]
Ok, I subscribed and it's still showing the old one but the message about not receiving updates is gone. Maybe push another change and it'll kick into life?

**Comment by M4rtineski** [comment]
Didn't find a setting to fetch an updated post or anything. We could either talk to some instance admins to ask how federation works (or doesn't) or have those questions at the top of our directory and hope someone here knows the answer.

**Comment by chris-y** [comment]
`[community name](/m/community@instance)` will work for k/Mbin

**Comment by M4rtineski** [comment]
Just noticed that I already ended up with this format while reformatting the links to allow more readable text with embedded links: 
![image](https://github.com/fnic-lemmy/lemmy-directory/assets/137183342/e9420be8-5c76-4df7-80d7-2a904ff1ef64)

But after testing it I discovered that this format doesn't work for lemmy so I will have to replace the "/m/" with "/c/" and see how it goes. Hopefully I will have only to change this one character to make xbin versions of links.

**Comment by M4rtineski** [comment]
I tried the "floating is fun" redirect and it didn't work. I will need to look if there are alternative redirects and if not then we will have to rely on lemmyverse.link for xbin redirects.

**Comment by M4rtineski** [comment]
It works with other instances. The problem was simply trying to go the the same instance through that link. It can be solved by using direct link and lemmyverse.link. Will be implementing alternative links today. Solved.
