### ISSUE TITLE
Should the comic section be under art section or somewhere else?

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#24]
Here's a list of comics I currently have: 

**[xkcd](/c/xkcd@lemmy.world)** | lemmy.world | [Kbin](/m/xkcd@lemmy.world) | [lemmyverse.link](https://lemmyverse.link/c/xkcd@lemmy.world) | ![](https://img.shields.io/lemmy/xkcd@lemmy.world?style=flat&label=Subs&color=pink)
**[unix_surrealism](/c/unix_surrealism@lemmy.sdf.org)** | lemmy.sdf.org | [Kbin](/m/unix_surrealism@lemmy.sdf.org) | [lemmyverse.link](https://lemmyverse.link/c/unix_surrealism@lemmy.sdf.org) | ![](https://img.shields.io/lemmy/unix_surrealism@lemmy.sdf.org?style=flat&label=Subs&color=pink)
**[The Far Side](/c/thefarside@sh.itjust.works)** | sh.itjust.works | [Kbin](/m/thefarside@sh.itjust.works) | [lemmyverse.link](https://lemmyverse.link/c/thefarside@sh.itjust.works) | ![](https://img.shields.io/lemmy/thefarside@sh.itjust.works?style=flat&label=Subs&color=pink)
**[Strange Planet by Nathan W. Pyle](/c/nathanwpyle@lemmy.world)** | lemmy.world | [Kbin](/m/nathanwpyle@lemmy.world) | [lemmyverse.link](https://lemmyverse.link/c/nathanwpyle@lemmy.world) | ![](https://img.shields.io/lemmy/nathanwpyle@lemmy.world?style=flat&label=Subs&color=pink)
**[Litterbox Comics](/c/litterboxcomics@lemmy.world)** | lemmy.world | [Kbin](/m/litterboxcomics@lemmy.world) | [lemmyverse.link](https://lemmyverse.link/c/litterboxcomics@lemmy.world) | ![](https://img.shields.io/lemmy/litterboxcomics@lemmy.world?style=flat&label=Subs&color=pink)
**[Heathcliff](/c/heathcliff@lemmy.world)** | lemmy.world | [Kbin](/m/heathcliff@lemmy.world) | [lemmyverse.link](https://lemmyverse.link/c/heathcliff@lemmy.world) | ![](https://img.shields.io/lemmy/heathcliff@lemmy.world?style=flat&label=Subs&color=pink)
**[Cyanide and Happiness](/c/cyanideandhappiness@lemm.ee)** | lemm.ee | [Kbin](/m/cyanideandhappiness@lemm.ee) | [lemmyverse.link](https://lemmyverse.link/c/cyanideandhappiness@lemm.ee) | ![](https://img.shields.io/lemmy/cyanideandhappiness@lemm.ee?style=flat&label=Subs&color=pink)

And then there are general comic communities:

**[Comics](/c/comics@lemmy.ml)** | lemmy.ml | [Kbin](/m/comics@lemmy.ml) | [lemmyverse.link](https://lemmyverse.link/c/comics@lemmy.ml) | ![](https://img.shields.io/lemmy/comics@lemmy.ml?style=flat&label=Subs&color=pink)
**[Comic Strips](/c/comicstrips@lemmy.world)** | lemmy.world | [Kbin](/m/comicstrips@lemmy.world) | [lemmyverse.link](https://lemmyverse.link/c/comicstrips@lemmy.world) | ![](https://img.shields.io/lemmy/comicstrips@lemmy.world?style=flat&label=Subs&color=pink)

**Comment by chris-y** [comment]
***@***.***
***@***.***
***@***.***
***@***.***

21 Jun 2024 08:49:50 M4rtineski ***@***.***>:

**Comment by chris-y** [comment]
Some more:

calvinandhobbes@lemmy.world
exocomics@lemmy.world
garfield@lemmy.world
loadingartist@lemmy.world

**Comment by M4rtineski** [comment]
Exocomics and loading artist weren't on my list yet. I will go ahead and include comics under art section and move it in the future if I find a better place for them.

**Comment by M4rtineski** [comment]
Comics are already in my local directory under art section.
