### ISSUE TITLE
Change how headers are set up.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#33]
![image](https://github.com/fnic-lemmy/lemmy-directory/assets/137183342/e96ea230-7be8-48e1-be2b-e0685fb14ecf)

Seems like a proper markdown practice unlike what I'm doing currently. Will fix this at the end of reorganising the current set of communities.

**Comment by M4rtineski** [comment]
@chris-y I can do this change right now. Do you want me to do it?

**Comment by chris-y** [comment]
Yes please! 

A more consistent format will definitely help.

**Comment by M4rtineski** [comment]
@chris-y Done.

**Comment by M4rtineski** [comment]
Forgot to mark it.
