### ISSUE TITLE
Reach out to communities/moderators to ask for community description for the directory?

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#35]
Many communities are missing one and I don't want to add them myself and risk describing communities badly.

**Comment by M4rtineski** [comment]
Naw, too much work and totally not worth it.

**Comment by chris-y** [comment]
Agreed - if anybody has a problem with their description, they'll tell us. We don't need to go and ask everyone.

**Comment by M4rtineski** [comment]
I think we should mention this in the intro post for the directory when it eventually comes: https://github.com/fnic-lemmy/lemmy-directory/issues/39
