### ISSUE TITLE
Do we even need to have the directory account marked as bot? After all there's no automation involved.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#4]
The directory is maintained fully manually, the bot has zero capabilities to do anything by itself and it's marked as a bot only because we use a github sync tool connected to a post made by this account to allow more people working on the directory. There are people that have bot visibility turned off and will miss the directory because of that.

**Comment by chris-y** [comment]
Hmm, it's a bit of a grey area. Maybe ask the server admin if they're ok with that?

**Comment by M4rtineski** [comment]
Admin said that that automatic copy/paste of the markdown into the body even though I'm spending hours on it and the automation saves a few minutes at most make the account a bot. Closed. :3

**Comment by M4rtineski** [comment]
We got a green light to be exempted from bot status.

**Comment by M4rtineski** [comment]
Well, I closed it before we even finished the task... Bringing it back now. xD

**Comment by chris-y** [comment]
I've unset the bot setting as I was in there to create the 2nd directory post.  I've put a note in the bio as to what it is used for and that we have permission for it to not be marked as a bot.

**Comment by M4rtineski** [comment]
Bringing it back because I want to change the wording a bit later. :3

**Comment by M4rtineski** [comment]
Changed my mind on the wording. It should be alright.

**Comment by M4rtineski** [comment]
Almost forgot to mention that, while going over the bots and adding my contact info I ultimately marked the directory sync account as a bot. :p

By extension of that I will mark it this way because the issue was about NOT marking it as such.
