### ISSUE TITLE
Comics

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/lemmy-directory#57]
comics@programming.dev is missing

**Comment by chris-y** [comment]
As is monkeyuser@programming.dev

**Comment by chris-y** [comment]
!moomin@sopuli.xyz also needs adding - I think this is fairly newly created.

**Comment by M4rtineski** [comment]
![image](https://github.com/user-attachments/assets/70fe7ac1-99bd-45bc-a9f8-611b9c532aaf)

While the posts are mostly comics it's a franchise and other content is allowed. Maybe we should organise a "franchise" category and then make use of that "you may also be interested in" category that we discussed in the past?

**Comment by chris-y** [comment]
Hmm, maybe it can go under "themes" for now?

**Comment by M4rtineski** [comment]
If we're talking about a temporary short-term solution then I'd rather simply put it in the comics and move it later.

**Comment by chris-y** [comment]
!truecomics@midwest.social

**Comment by chris-y** [comment]
This one has just popped up:
!peanuts@midwest.social

**Comment by M4rtineski** [comment]
Added them all to my local directory.
