### ISSUE TITLE
Dubstep move to db0

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/lemmy-directory#59]
https://lemmy.world/post/18587289

Helpfully highlighted by bestofbot!

**Comment by M4rtineski** [comment]
Ooooh, I saw it on the trending bar some days ago and had a thought that it may have been on a different instance but dismissed it as me confusing this community with some other. Good to know that it moved from LW. Will edit it into the directory later.

**Comment by M4rtineski** [comment]
Added it to my local directory.
