### ISSUE TITLE
We need to check if there are shields for kbin/mbin and implement them into the directory.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/lemmy-directory#6]

**Comment by chris-y** [comment]
We will need to raise a feature request for this. 
Worse case they can scrape the information from the magazine page or the magazine search. 
https://fedia.io/magazines?query=teletext&fields=names&federation=local&adult=show

I don't think there's any API to show the value. 

Actually, the Activity pub API can probably provide this.

**Comment by chris-y** [comment]
Step 1: https://github.com/MbinOrg/mbin/issues/832

**Comment by chris-y** [comment]
Step 2: https://github.com/badges/shields/issues/10264

I think that should work with kbin as well, but I'm not sure if the state of the API there. I know it was taking ages for it to be in the stable branch.

**Comment by chris-y** [comment]
I've managed to add Mbin support to shields.io :smiley: 
![image](https://github.com/fnic-lemmy/lemmy-directory/assets/1818803/dc426978-2eb0-4c2a-898e-72297ca04a01)

I need to add some tests apparently, haven't looked into that bit yet.

**Comment by M4rtineski** [comment]
Is this really shields.io or did you use a workaround? The URL looks different from shields.io.

**Comment by M4rtineski** [comment]
Ah, forgot to be happy about that. I'm happy we finally got it working. :3

**Comment by chris-y** [comment]
Awaiting merge: https://github.com/badges/shields/pull/10270

Something to be aware of is that Mbin is case sensitive with the magazine names.

**Comment by M4rtineski** [comment]
If I'm not missing anything then this issue got resolved.
