### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/lemmy-directory#64]
New community:
!dragons@pawb.social

**Comment by M4rtineski** [comment]
Oh? Seems to be a new community. I'm pretty sure there was a community like that there already though? Or maybe it was just dragon related and not general like this one.

**Comment by chris-y** [comment]
There's Imaginary Dragons of course. 

There's wizards, but they aren't dragons, however dragons might turn up there.

**Comment by M4rtineski** [comment]
Ah, I didn't mean imaginary dragons, I think there was something else dragon related from the furry community but I think it must have been something more specific if this new community was created. :p

**Comment by chris-y** [comment]
There's DND on blahaj: https://lemmy.blahaj.zone/c/dnd

**Comment by M4rtineski** [comment]
Added 'dragons' to my local version.
